.PHONY: help setup up down build logs shell-django shell-vue migrate migration test clean restart status

# Default target
help:
	@echo "Available commands:"
	@echo "  make setup           - Initial setup for new developers"
	@echo "  make up              - Start all services"
	@echo "  make down            - Stop all services"
	@echo "  make build           - Full rebuild (no cache)"
	@echo "  make logs            - View logs from all services"
	@echo "  make shell-django    - Open shell in Django container"
	@echo "  make shell-vue       - Open shell in Vue container"
	@echo "  make migrate         - Run Django migrations"
	@echo "  make migration       - Create Django migrations"
	@echo "  make superuser       - Create Django superuser"
	@echo "  make test            - Run Django tests"
	@echo "  make clean           - Remove all containers and volumes"
	@echo "  make restart         - Restart all services"
	@echo "  make status          - Show container status"

# Initial setup for new developers
setup:
	@echo "🚀 Setting up Gelt development environment..."
	@if [ -f .env ]; then \
		echo "⚠️  .env file already exists. Skipping creation."; \
	else \
		echo "# Generated by 'make setup' on $$(date)" > .env; \
		echo "ENVIRONMENT=development" >> .env; \
		echo "BASE_DOMAIN=localhost" >> .env; \
		echo "" >> .env; \
		echo "# Django settings" >> .env; \
		echo "DJANGO_SECRET_KEY=$$(python3 -c 'import secrets; print(secrets.token_urlsafe(50))')" >> .env; \
		echo "DATABASE_NAME=db.sqlite3" >> .env; \
		echo "" >> .env; \
		echo "# Email for SSL certificates" >> .env; \
		echo "CADDY_EMAIL=admin@example.com" >> .env; \
		echo "" >> .env; \
		echo "# Container ports" >> .env; \
		echo "DJANGO_PORT=8000" >> .env; \
		echo "VUE_PORT=5173" >> .env; \
		echo "" >> .env; \
		echo "# Logging" >> .env; \
		echo "LOG_LEVEL=INFO" >> .env; \
	fi
	@docker-compose build --quiet
	@docker-compose up -d
	@sleep 10
	@docker-compose exec server python manage.py migrate
	@echo ""
	@echo "✅ Setup complete! Your application is running at:"
	@echo "   Frontend: http://localhost"
	@echo "   API: http://api.localhost"
	@echo ""
	@echo "👤 Next step: Create a superuser with 'make superuser'"

# Start services 
up:
	docker-compose up -d
	@echo "Services started. Access the app at:"
	@echo "  CLIENT: http://$(shell grep BASE_DOMAIN .env | cut -d '=' -f2):$(shell grep VUE_PORT .env | cut -d '=' -f2)"
	@echo "  SERVER: http://api.$(shell grep BASE_DOMAIN .env | cut -d '=' -f2):$(shell grep DJANGO_PORT .env | cut -d '=' -f2)"

# Stop services
down:
	docker-compose down

# Build containers (full rebuild, no cache)
build:
	docker-compose build --no-cache

# View logs
logs:
	docker-compose logs -f

# Shell access
shell-django:
	docker-compose exec server /bin/sh

shell-vue:
	docker-compose exec client /bin/sh

# Django commands
migrate:
	docker-compose exec server python manage.py migrate

migration:
	docker-compose exec server python manage.py makemigration

superuser:
	docker-compose exec -it server python manage.py createsuperuser

test:
	docker-compose exec server python manage.py test

# Clean everything
clean:
	docker-compose down -v
	rm -rf data/*.sqlite3
	@echo "Cleaned all containers and volumes"

# Restart services
restart:
	docker-compose restart

# Show status
status:
	docker-compose ps

# Development specific commands
dev-install:
	docker-compose exec client npm install

dev-django-shell:
	docker-compose exec server python manage.py shell

# Production build
prod-build:
	ENVIRONMENT=production docker-compose build

prod-up:
	ENVIRONMENT=production docker-compose up -d